apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: wardtide
commonLabels:
  app: wardtide
resources:
- deployment.yml
- service.yml
configMapGenerator:
  - name: pia-config
    literals:
      - PIA_DNS=false
      - PIA_PF=true
      - AUTOCONNECT=true
      - VPN_PROTOCOL=openvpn_tcp_strong
      - DISABLE_IPV6=true
secretGenerator:
- name: pia-pass
  envs:
  - vars.env