apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: wardtide
commonLabels:
  app: wardtide
resources:
- deployment.yml
- service.yml
- wireguard-svc.yaml
- pia_sealed.yaml
configMapGenerator:
  - name: pia-config
    literals:
      - PIA_DNS=true
      - PIA_PF=false
      - AUTOCONNECT=true
      - VPN_PROTOCOL=wireguard
      - DISABLE_IPV6=true
      - LAN_NETWORK="10.0.0.0/8"
