apiVersion: v1
kind: Service
metadata:
  name: wardtide
spec:
  selector:
    app: wardtide
  type: LoadBalancer
  ports:
  - name: transmission
    port: 80
    targetPort: 8080
  - name: tinyproxy
    port: 8888
    targetPort: 8888
